import { appendFileSync, existsSync, readFileSync, statSync, readdirSync } from "node:fs";
import { exec as execCallback } from "node:child_process";
import { promisify } from "node:util";
import { resolve, relative, join, basename, sep } from "node:path";
import { buildReleasePlan } from "./release.js";
import { parseChange } from "./changes.js";
import { parseConfig, withOverrides } from "./config.js";
import { readinessMarkdown } from "./readiness.js";
import { releaseTagName, GitHubClient, type GitHubCommitSummary, type GitHubPullRequest } from "./github.js";
import { readPackageVersion, updateVersionFiles } from "./version-files.js";
import type { ReleasePlan, ShipkitConfig } from "./types.js";

const exec = promisify(execCallback);

interface PushEvent {
  ref?: string;
  after?: string;
}

interface PullRequestEvent {
  action?: string;
  pull_request?: GitHubPullRequest & { merged?: boolean };
}

function input(name: string): string {
  return process.env[`INPUT_${name.toUpperCase().replace(/ /g, "_")}`]?.trim() ?? "";
}

function setOutput(name: string, value: string): void {
  const outputFile = process.env.GITHUB_OUTPUT;
  if (!outputFile) {
    return;
  }
  const delimiter = `SHIPKIT_${Date.now()}_${Math.random().toString(16).slice(2)}`;
  appendFileSync(outputFile, `${name}<<${delimiter}\n${value}\n${delimiter}\n`, "utf8");
}

function log(message: string): void {
  process.stdout.write(`[shipkit] ${message}\n`);
}

function readEvent(): PushEvent | PullRequestEvent {
  const eventPath = process.env.GITHUB_EVENT_PATH;
  if (!eventPath || !existsSync(eventPath)) {
    return {};
  }
  return JSON.parse(readFileSync(eventPath, "utf8")) as PushEvent | PullRequestEvent;
}

function isDryRun(): boolean {
  return input("dry-run").toLowerCase() === "true";
}

function pullRequestChange(pr: GitHubPullRequest) {
  return parseChange({
    title: pr.title,
    body: pr.body ?? "",
    source: "pull_request",
    number: pr.number,
    url: pr.html_url,
    labels: pr.labels.map((label) => label.name),
    mergedAt: pr.merged_at ?? undefined,
    sha: pr.merge_commit_sha ?? undefined
  });
}

function commitChange(commit: GitHubCommitSummary) {
  return parseChange({
    title: commit.commit.message.split(/\r?\n/, 1)[0] ?? commit.commit.message,
    body: commit.commit.message,
    source: "commit",
    sha: commit.sha,
    url: commit.html_url,
    author: commit.commit.author?.name,
    mergedAt: commit.commit.author?.date
  });
}

async function changesSinceTag(client: GitHubClient, head: string, tag: string | null) {
  const commits = tag ? (await client.compare(tag, head)).commits : await client.listCommits(head);
  const pullRequests = new Map<number, GitHubPullRequest>();
  const changes = [];
  for (const commit of commits) {
    const associated = await client.commitPullRequests(commit.sha);
    if (associated.length === 0) {
      changes.push(commitChange(commit));
      continue;
    }
    for (const pr of associated) {
      if (pr.merged_at && !pullRequests.has(pr.number)) {
        pullRequests.set(pr.number, pr);
      }
    }
  }
  changes.push(...[...pullRequests.values()].map(pullRequestChange));
  return changes;
}

async function latestReleaseTag(client: GitHubClient, config: ShipkitConfig): Promise<string | null> {
  const { parseVersion, compareVersions } = await import("./semver.js");
  let selected: { name: string; version: string } | null = null;
  for (const tag of await client.listTags()) {
    const value = tag.name.startsWith(config.release.tagPrefix) ? tag.name.slice(config.release.tagPrefix.length) : tag.name;
    if (!parseVersion(value)) {
      continue;
    }
    if (!selected || compareVersions(value, selected.version) > 0) {
      selected = { name: tag.name, version: value };
    }
  }
  return selected?.name ?? null;
}

async function loadConfig(client: GitHubClient, path: string, ref: string): Promise<ShipkitConfig> {
  const content = await client.getFile(path, ref);
  return content ? parseConfig(content, path) : parseConfig("");
}

function releasePrBody(plan: ReleasePlan, config: ShipkitConfig): string {
  const marker = JSON.stringify({ version: plan.version, manifest: config.outputs.manifest });
  const lines = [
    `<!-- shipkit-release ${marker} -->`,
    `# Shipkit release ${plan.version}`,
    "",
    `This release updates the package from **${plan.previousVersion}** to **${plan.version}** and prepares the release communication files.`,
    "",
    readinessMarkdown(plan.readiness).trim(),
    "",
    "## Customer-facing notes",
    "",
    plan.customerNotes.trim(),
    "",
    "---",
    "Generated by Shipkit. Merge this pull request to publish the tag and GitHub release."
  ];
  return `${lines.join("\n").trim()}\n`;
}

function fileMapFromPlan(plan: ReleasePlan): Record<string, string> {
  return Object.fromEntries(plan.outputs.map((output) => [output.path, output.content]));
}

async function runReadinessCommands(config: ShipkitConfig): Promise<Record<string, boolean>> {
  const results: Record<string, boolean> = {};
  const workspace = process.env.GITHUB_WORKSPACE ?? process.cwd();
  for (const command of config.readiness.commands) {
    try {
      log(`Running readiness check: ${command.name}`);
      await exec(command.run, { cwd: workspace, shell: process.env.ComSpec ?? "/bin/sh", maxBuffer: 1024 * 1024 * 20 });
      results[command.name] = true;
    } catch {
      results[command.name] = false;
      log(`Readiness check failed: ${command.name}`);
    }
  }
  return results;
}

async function prepareRelease(client: GitHubClient, head: string, config: ShipkitConfig): Promise<void> {
  const packageJson = await client.getFile("package.json", head);
  if (!packageJson) {
    throw new Error("Shipkit requires package.json in the repository root for the Node.js v1 release path.");
  }
  const currentVersion = readPackageVersion(packageJson);
  const existingChangelog = await client.getFile(config.outputs.changelog, head) ?? "";
  const changes = await changesSinceTag(client, head, await latestReleaseTag(client, config));
  const betaLabelPresent = changes.some((change) => change.labels.includes("ship:beta"));
  const effectiveConfig = betaLabelPresent && !config.release.prerelease ? withOverrides(config, { prerelease: "beta" }) : config;
  const availableLabels = new Set(changes.flatMap((change) => change.labels));
  const availableFiles = new Set<string>();
  for (const requiredFile of effectiveConfig.readiness.requiredFiles) {
    if (await client.getFile(requiredFile, head)) {
      availableFiles.add(requiredFile);
    }
  }
  const plan = buildReleasePlan({
    currentVersion,
    changes,
    config: effectiveConfig,
    existingChangelog: await client.getFile(effectiveConfig.outputs.changelog, head) ?? existingChangelog,
    readinessContext: { availableLabels, availableFiles, commandResults: await runReadinessCommands(effectiveConfig) }
  });
  setOutput("version", plan.version);
  if (!plan.hasRelease) {
    log("No release-worthy changes were found.");
    return;
  }
  log(`Planned ${plan.version} (${plan.bump}) from ${plan.releaseChanges.length} change(s).`);
  if (isDryRun()) {
    log(JSON.stringify(plan, null, 2));
    return;
  }

  const repository = await client.repositoryInfo();
  const baseCommit = await client.getCommit(head);
  const versionFiles = {
    "package.json": packageJson,
    ...(await client.getFile("package-lock.json", head) ? { "package-lock.json": (await client.getFile("package-lock.json", head)) as string } : {}),
    ...(await client.getFile("npm-shrinkwrap.json", head) ? { "npm-shrinkwrap.json": (await client.getFile("npm-shrinkwrap.json", head)) as string } : {})
  };
  const entries = new Map<string, string>(Object.entries(fileMapFromPlan(plan)));
  for (const change of updateVersionFiles(versionFiles, plan.version)) {
    entries.set(change.path, change.content);
  }
  const tree = await client.createTree(baseCommit.tree.sha, [...entries].map(([path, content]) => ({ path, mode: "100644", type: "blob", content })));
  const commit = await client.createCommit(`chore(release): prepare ${releaseTagName(effectiveConfig.release.tagPrefix, plan.version)}`, tree.sha, head);
  const branchRef = `heads/${effectiveConfig.release.branch}`;
  if (await client.getRef(branchRef)) {
    await client.updateRef(branchRef, commit.sha, true);
  } else {
    await client.createRef(branchRef, commit.sha);
  }

  const title = `chore(release): ${releaseTagName(effectiveConfig.release.tagPrefix, plan.version)}`;
  const body = releasePrBody(plan, effectiveConfig);
  const existing = (await client.listPullRequests({ state: "open", head: `${repository.owner.login}:${effectiveConfig.release.branch}`, base: repository.default_branch }))[0];
  const releasePr = existing ? await client.updatePullRequest(existing.number, { title, body }) : await client.createPullRequest({ title, body, head: effectiveConfig.release.branch, base: repository.default_branch });
  setOutput("release-pr", releasePr.html_url);
  log(`${existing ? "Updated" : "Created"} release PR: ${releasePr.html_url}`);
}

function isShipkitReleasePullRequest(pr: GitHubPullRequest): boolean {
  return pr.head.ref.startsWith("shipkit/") && /release/i.test(pr.title);
}

function collectFiles(target: string, root: string): string[] {
  const absolute = resolve(root, target);
  const relativePath = relative(root, absolute);
  if (relativePath === ".." || relativePath.startsWith(`..${sep}`)) {
    throw new Error(`Artifact path must stay inside the workspace: ${target}`);
  }
  if (!existsSync(absolute)) {
    throw new Error(`Expected artifact does not exist: ${target}`);
  }
  if (statSync(absolute).isFile()) {
    return [absolute];
  }
  return readdirSync(absolute, { withFileTypes: true }).flatMap((entry) => collectFiles(join(target, entry.name), root));
}

async function publishRelease(client: GitHubClient, pr: GitHubPullRequest, config: ShipkitConfig): Promise<void> {
  const mergeSha = pr.merge_commit_sha;
  if (!mergeSha) {
    throw new Error("The Shipkit release PR does not have a merge commit SHA.");
  }
  const packageJson = await client.getFile("package.json", mergeSha);
  if (!packageJson) {
    throw new Error("The merged Shipkit release PR does not contain package.json.");
  }
  const version = readPackageVersion(packageJson);
  const manifestContent = await client.getFile(config.outputs.manifest, mergeSha);
  if (manifestContent) {
    const manifest = JSON.parse(manifestContent) as { readiness?: { passed?: boolean } };
    if (manifest.readiness?.passed === false) {
      throw new Error("Release readiness checks are incomplete; Shipkit did not publish the release.");
    }
  }
  const tag = releaseTagName(config.release.tagPrefix, version);
  if (!await client.getRef(`tags/${tag}`)) {
    await client.createRef(`tags/${tag}`, mergeSha);
  }
  const existingRelease = await client.getReleaseByTag(tag);
  const customerNotes = await client.getFile(config.outputs.customerNotes, mergeSha) ?? `Release ${version}`;
  const release = existingRelease ?? await client.createRelease({
    tag_name: tag,
    target_commitish: mergeSha,
    name: tag,
    body: customerNotes,
    prerelease: Boolean(version.includes("-"))
  });
  setOutput("version", version);
  setOutput("release-url", release.html_url);
  log(`${existingRelease ? "Found" : "Published"} GitHub release: ${release.html_url}`);

  const artifactCommand = input("artifact-command") || config.artifacts.command;
  const workspace = process.env.GITHUB_WORKSPACE ?? process.cwd();
  if (artifactCommand) {
    log(`Running artifact command: ${artifactCommand}`);
    await exec(artifactCommand, { cwd: workspace, shell: process.env.ComSpec ?? "/bin/sh", maxBuffer: 1024 * 1024 * 20 });
  }
  const artifactFiles = config.artifacts.paths.flatMap((path) => collectFiles(path, workspace));
  for (const file of artifactFiles) {
    await client.uploadReleaseAsset(release, file);
    log(`Uploaded release artifact: ${basename(file)}`);
  }
}

export async function run(): Promise<void> {
  const token = input("github-token") || process.env.GITHUB_TOKEN || "";
  const repository = process.env.GITHUB_REPOSITORY;
  if (!repository) {
    throw new Error("GITHUB_REPOSITORY is required.");
  }
  const client = new GitHubClient(token, repository);
  const eventName = process.env.GITHUB_EVENT_NAME ?? "";
  const event = readEvent();
  const configPath = input("config") || ".shipkit.yml";
  const pullRequestMergeSha = "pull_request" in event ? event.pull_request?.merge_commit_sha ?? undefined : undefined;
  const ref = pullRequestMergeSha || process.env.GITHUB_SHA || ("after" in event ? event.after : undefined) || "HEAD";
  const config = withOverrides(await loadConfig(client, configPath, ref), {
    prerelease: input("prerelease"),
    artifactCommand: input("artifact-command")
  });

  if (eventName === "pull_request" && "pull_request" in event && event.pull_request && event.action === "closed" && event.pull_request.merged && isShipkitReleasePullRequest(event.pull_request)) {
    await publishRelease(client, event.pull_request, config);
    return;
  }
  if (eventName !== "push") {
    log(`Ignoring event ${eventName || "unknown"}; Shipkit runs on pushes and merged pull requests.`);
    return;
  }
  const repositoryInfo = await client.repositoryInfo();
  const push = event as PushEvent;
  const expectedRef = `refs/heads/${repositoryInfo.default_branch}`;
  if (push.ref && push.ref !== expectedRef) {
    log(`Ignoring push to ${push.ref}; release preparation runs on ${expectedRef}.`);
    return;
  }
  await prepareRelease(client, push.after || process.env.GITHUB_SHA || "", config);
}

if (process.env.NODE_ENV !== "test") {
  run().catch((error: unknown) => {
    process.stderr.write(`[shipkit] ${error instanceof Error ? error.stack ?? error.message : String(error)}\n`);
    process.exitCode = 1;
  });
}
